set MATLAB=C:/Program Files/MATLAB/R2009b
"%MATLAB%\bin\win32\gmake.exe" -f Simplest_With_For_Iterator2.mk  GENERATE_REPORT=0 PORTABLE_WORDSIZES=0 GENERATE_ASAP2=0 TMW_EXTMODE_TESTING=0 MPC555_OPTIMIZATION_SWITCH="speed" EXECUTION_PROFILING_ENABLED=0 EXECUTION_PROFILING_NUM_SAMPLES=500 RELATIVE_PATH_TO_ANCHOR=..
